import type { RegulatoryFramework } from "../types";

export const BR_FRAMEWORKS: RegulatoryFramework[] = [
  {
    id: "BR_ANVISA",
    countryCode: "BR",
    countryName: "Brazil",
    flag: "🇧🇷",
    authority: "ANVISA",
    documentType: "Registration Dossier (RDC 751/2022)",
    sections: [
      {
        id: "s1",
        title: "Administrative Information",
        description: "Applicant identification, legal representation, and regulatory prerequisites",
        fields: [
          { id: "1.1", label: "Applicant (Registration Holder)", hint: "Brazilian legal entity name, CNPJ, and address that will hold the product registration with ANVISA" },
          { id: "1.2", label: "Brazilian Registration Holder (BRH)", hint: "Designated BRH responsible for regulatory compliance in Brazil, including Autorização de Funcionamento (AFE) number" },
          { id: "1.3", label: "Legal Representative", hint: "Legally appointed representative in Brazil authorized to act on behalf of the foreign manufacturer before ANVISA" },
          { id: "1.4", label: "Digital Certificate (ICP-Brasil)", hint: "Valid ICP-Brasil e-CPF or e-CNPJ digital certificate required for electronic submission via ANVISA portal" },
          { id: "1.5", label: "GMP/BGMP Certificate", hint: "Certificado de Boas Práticas de Fabricação (CBPF) issued by ANVISA after inspection or via MDSAP recognition" },
          { id: "1.6", label: "Establishment Licence (AFE)", hint: "Autorização de Funcionamento de Empresa issued by ANVISA for importation, distribution, or manufacturing activities" },
          { id: "1.7", label: "CNPJ Number", hint: "Cadastro Nacional da Pessoa Jurídica — Brazilian federal tax registration number of the registration holder" },
        ],
      },
      {
        id: "s2",
        title: "Device Description",
        description: "Technical characterization, classification, and device family definition",
        fields: [
          { id: "2.1", label: "Device Description", hint: "Detailed technical description including design, dimensions, materials, and functional characteristics per RDC 751/2022 Annex II", textarea: true },
          { id: "2.2", label: "Intended Use / Intended Purpose", hint: "Precise statement of intended medical purpose, target population, medical condition, and clinical context in Portuguese", textarea: true },
          { id: "2.3", label: "ANVISA Classification", hint: "Risk classification (Class I, II, III, or IV) per ANVISA classification rules in RDC 751/2022 Annex III with rule number cited" },
          { id: "2.4", label: "Composition & Materials", hint: "Complete list of materials in contact with body/sample with biocompatibility references (e.g., ASTM F138, USP Class VI)", textarea: true },
          { id: "2.5", label: "Technical Specifications", hint: "Measurable performance specifications including dimensions, tolerances, electrical ratings, and output parameters", textarea: true },
          { id: "2.6", label: "Variants & Configurations", hint: "All device models, sizes, and configurations included in the registration family with justification for grouping", textarea: true },
          { id: "2.7", label: "Accessories & Companion Devices", hint: "List of accessories, ancillary devices, and combination products required for intended operation with regulatory status of each" },
          { id: "2.8", label: "Software Documentation", hint: "Software level of concern, architecture description, IEC 62304 lifecycle documentation, and SaMD classification if applicable", textarea: true },
        ],
      },
      {
        id: "s3",
        title: "Essential Safety & Performance Requirements",
        description: "Demonstration of conformity with essential principles",
        fields: [
          { id: "3.1", label: "Risk Analysis (ISO 14971)", hint: "Complete risk management file per ISO 14971:2019 including risk management plan, FMEA/FTA, risk evaluation, and risk management report", textarea: true },
          { id: "3.2", label: "Essential Principles Checklist", hint: "Clause-by-clause compliance checklist against RDC 751/2022 Annex I essential safety and performance requirements with evidence references", textarea: true },
          { id: "3.3", label: "Standards Applied", hint: "List of ABNT NBR, IEC, and ISO standards applied with declaration of full or partial conformity for each", textarea: true },
          { id: "3.4", label: "Biocompatibility Evaluation", hint: "Biological evaluation per ISO 10993-1 with endpoint selection rationale based on body contact nature and duration", textarea: true },
          { id: "3.5", label: "Electrical Safety", hint: "IEC 60601-1 Ed. 3.2 test report and applicable particular/collateral standards for electrically powered devices", textarea: true },
          { id: "3.6", label: "Electromagnetic Compatibility (EMC)", hint: "IEC 60601-1-2 Ed. 4.1 EMC test report including immunity and emissions testing in intended electromagnetic environment", textarea: true },
          { id: "3.7", label: "Sterilization Validation", hint: "Validation of terminal sterilization (ISO 11135, ISO 11137, ISO 17665) or aseptic processing with sterility assurance level (SAL) 10⁻⁶", textarea: true },
          { id: "3.8", label: "Shelf Life / Stability", hint: "Real-time and accelerated aging studies per ASTM F1980 with sterile barrier integrity testing per ISO 11607", textarea: true },
        ],
      },
      {
        id: "s4",
        title: "Verification & Validation",
        description: "Design verification testing and performance validation",
        fields: [
          { id: "4.1", label: "Bench Testing Summary", hint: "Design verification test reports demonstrating device meets design output specifications under simulated and worst-case conditions", textarea: true },
          { id: "4.2", label: "Analytical Performance", hint: "For IVDs: analytical sensitivity, specificity, precision, accuracy, linearity, measuring range, and interfering substances studies", textarea: true },
          { id: "4.3", label: "Simulated Use Testing", hint: "Usability validation per IEC 62366-1 including formative and summative human factors testing with representative users", textarea: true },
          { id: "4.4", label: "Software Verification & Validation", hint: "Software V&V per IEC 62304 including unit testing, integration testing, system testing, and regression testing documentation", textarea: true },
          { id: "4.5", label: "Usability Engineering File", hint: "Human factors engineering report per IEC 62366-1 with use-related risk analysis, formative evaluations, and summative validation", textarea: true },
        ],
      },
      {
        id: "s5",
        title: "Clinical Evidence",
        description: "Clinical data supporting safety and performance claims",
        fields: [
          { id: "5.1", label: "Clinical Evaluation Report", hint: "Systematic and planned assessment of clinical data per MEDDEV 2.7/1 Rev 4 or ANVISA guidance demonstrating benefit-risk acceptability", textarea: true },
          { id: "5.2", label: "Clinical Investigation Summary", hint: "If conducted: GCP-compliant study per ISO 14155 with protocol synopsis, primary/secondary endpoints, results, and adverse events", textarea: true },
          { id: "5.3", label: "Literature Review", hint: "Structured literature search with databases searched, search terms, PICO framework, critical appraisal, and data synthesis", textarea: true },
        ],
      },
      {
        id: "s6",
        title: "Labelling & Instructions for Use",
        description: "Portuguese-language labelling and UDI compliance",
        fields: [
          { id: "6.1", label: "Device Labels (Portuguese)", hint: "All labels in Brazilian Portuguese per RDC 751/2022 labelling requirements including ANVISA registration number and manufacturer", textarea: true },
          { id: "6.2", label: "Instructions for Use (Portuguese)", hint: "Complete IFU in Portuguese with indications, contraindications, warnings, precautions, preparation, operation, and maintenance", textarea: true },
          { id: "6.3", label: "Packaging Labels", hint: "Inner and outer packaging labels with lot/serial number, manufacture date, expiry date, storage conditions, and sterility indicators" },
          { id: "6.4", label: "UDI Implementation", hint: "Unique Device Identification per ANVISA UDI requirements including UDI-DI, UDI-PI, and ANVISA database registration" },
        ],
      },
      {
        id: "s7",
        title: "Manufacturing & Quality System",
        description: "Manufacturing processes and GMP/BGMP compliance",
        fields: [
          { id: "7.1", label: "Process Flowchart", hint: "Manufacturing process flow from incoming materials to finished device release including QC hold points and critical process steps", textarea: true },
          { id: "7.2", label: "Manufacturing Facilities", hint: "Name, address, and ANVISA GMP status of each manufacturing, sterilization, and packaging site with scope of activities" },
          { id: "7.3", label: "GMP/BGMP Compliance", hint: "Evidence of BGMP (Boas Práticas de Fabricação) compliance via ANVISA CBPF certificate or MDSAP audit report covering Brazil", textarea: true },
          { id: "7.4", label: "Quality Management System", hint: "ISO 13485:2016 certification scope covering all devices and processes included in the registration, issued by IAF-accredited body" },
          { id: "7.5", label: "Contract Manufacturing & Sterilization", hint: "Names, addresses, and ANVISA GMP status of contract manufacturers and sterilization service providers with quality agreements" },
        ],
      },
      {
        id: "s8",
        title: "Post-Market Surveillance",
        description: "Technovigilance, complaints, and periodic reporting",
        fields: [
          { id: "8.1", label: "Technovigilance Plan", hint: "Post-market surveillance plan per ANVISA technovigilance requirements including reportable event criteria and NOTIVISA reporting procedures", textarea: true },
          { id: "8.2", label: "Complaint Handling System", hint: "Procedure for receiving, investigating, and trending complaints with timelines for technovigilance notification to ANVISA", textarea: true },
          { id: "8.3", label: "CAPA System", hint: "Corrective and preventive action procedures linked to complaint trends, audit findings, and technovigilance events", textarea: true },
          { id: "8.4", label: "Periodic Safety Reports", hint: "Post-market periodic reports (PSUR equivalent) summarizing safety data, complaint trends, and benefit-risk re-evaluation", textarea: true },
        ],
      },
      {
        id: "s9",
        title: "Certificates & Foreign Approvals",
        description: "Supporting certificates and international regulatory status",
        fields: [
          { id: "9.1", label: "Certificate of Free Sale", hint: "Government-issued certificate confirming the device is freely marketed in the country of origin, apostilled or consularized" },
          { id: "9.2", label: "ISO 13485 Certificate", hint: "Current ISO 13485:2016 certificate with scope of certification, issuing body accreditation, and expiry date" },
          { id: "9.3", label: "CE Marking (if applicable)", hint: "EC/EU Declaration of Conformity and Notified Body certificate under MDD 93/42/EEC or MDR 2017/745 if CE marked" },
          { id: "9.4", label: "Foreign Regulatory Approvals (AREE)", hint: "Summary of approvals in reference countries (US FDA, EU, Japan, Canada, Australia) as evidence of regulatory equivalence", textarea: true },
        ],
      },
      {
        id: "s10",
        title: "Country-Specific Requirements",
        description: "Brazil-specific regulatory and administrative requirements",
        fields: [
          { id: "10.1", label: "INMETRO Certification", hint: "Compulsory INMETRO conformity assessment certificate for devices under mandatory certification regime (e.g., electromedical equipment per Portaria 54)" },
          { id: "10.2", label: "Portuguese Translation Requirements", hint: "Sworn translation (tradução juramentada) requirements for foreign-language technical documents submitted to ANVISA" },
          { id: "10.3", label: "Local Representative Obligations", hint: "BRH responsibilities including adverse event reporting, registration maintenance, import authorization, and post-market obligations per RDC 751/2022", textarea: true },
          { id: "10.4", label: "ANVISA Registration Fee", hint: "Applicable Taxa de Fiscalização de Vigilância Sanitária (TFVS) fee category and payment confirmation (GRU)" },
          { id: "10.5", label: "Petição Eletrônica Submission", hint: "Electronic petition submission via ANVISA Solicita system including required document format (PDF/A) and file naming conventions" },
          { id: "10.6", label: "ANVISA Registration Fee (TFVS)", hint: "Applicable fee category under Taxa de Fiscalização de Vigilância Sanitária with GRU payment receipt and validity period" },
          { id: "10.7", label: "Regularization Pathway", hint: "Registration type: cadastro (Class I/II), registro (Class III/IV), or notificação with applicable timelines under RDC 751/2022" },
        ],
      },
    ],
  },
];
