import type { RegulatoryFramework } from "../types";

export const SA_FRAMEWORKS: RegulatoryFramework[] = [
  {
    id: "SA_SFDA",
    countryCode: "SA",
    countryName: "Saudi Arabia",
    flag: "🇸🇦",
    authority: "SFDA",
    documentType: "Medical Device Marketing Authorization",
    sections: [
      {
        id: "s1",
        title: "Administrative Information",
        description: "Applicant identification, authorized representation, and device listing details for SFDA submission",
        fields: [
          { id: "1.1", label: "Applicant (Registration Holder)", hint: "Legal entity name, address, and SFDA-issued establishment license number of the company applying for the Medical Device Marketing Authorization (MDMA)" },
          { id: "1.2", label: "MDMA Authorized Representative", hint: "Authorized representative designated under SFDA IR-MDR Chapter 3 to act on behalf of the foreign manufacturer, including their SFDA establishment license" },
          { id: "1.3", label: "Saudi Agent / Importer", hint: "Saudi-based agent or importer holding a valid SFDA establishment license with commercial registration (CR) number and Saudi address" },
          { id: "1.4", label: "Device Name (Arabic)", hint: "Official device name in Arabic as it will appear on the SFDA MDMA certificate and Arabic-language labelling" },
          { id: "1.5", label: "Device Name (English)", hint: "Official device name in English matching the manufacturer's marketing name, model numbers, and catalogue references" },
          { id: "1.6", label: "SFDA Listing Number", hint: "Existing SFDA medical device listing number if previously registered; leave blank for new applications. Reference SFDA e-services portal listing" },
          { id: "1.7", label: "GTIN / UDI", hint: "Global Trade Item Number and Unique Device Identifier per SFDA UDI implementation requirements aligned with IMDRF UDI guidance" },
        ],
      },
      {
        id: "s2",
        title: "Device Description",
        description: "Comprehensive technical characterization of the device per SFDA IR-MDR Annex II requirements",
        fields: [
          { id: "2.1", label: "Device Description", hint: "Detailed technical description including design, dimensions, weight, materials, functional principles, and performance characteristics per SFDA IR-MDR Annex II Section 1", textarea: true },
          { id: "2.2", label: "Intended Purpose", hint: "Precise statement of the medical purpose per SFDA IR-MDR Article 2 including target condition, patient population, intended user, and clinical context", textarea: true },
          { id: "2.3", label: "SFDA Classification", hint: "Risk classification per SFDA classification rules: Class I, IIa, IIb, III, or IV with specific classification rule number cited from SFDA IR-MDR Annex VIII" },
          { id: "2.4", label: "Materials & Composition", hint: "Complete bill of materials for patient-contacting and critical components including material grades, biological origin, and substances of toxicological concern", textarea: true },
          { id: "2.5", label: "Key Components", hint: "List of all critical subassemblies and functional components with part numbers, specifications, and supplier qualification status" },
          { id: "2.6", label: "Software Information", hint: "Software version, level of concern, SaMD classification per IMDRF, IEC 62304 lifecycle class, SOUP list, and cybersecurity documentation per SFDA guidance", textarea: true },
          { id: "2.7", label: "Accessories", hint: "All accessories required for intended operation with individual regulatory status, compatibility specifications, and SFDA listing status for each" },
          { id: "2.8", label: "Variants & Configurations", hint: "All models, sizes, and configurations included in the MDMA application with justification for grouping as a single device family" },
          { id: "2.9", label: "Sterilization Method", hint: "Terminal sterilization method (EtO, gamma, e-beam, steam) or aseptic processing with sterility assurance level (SAL) of 10⁻⁶ and reprocessing instructions if reusable" },
        ],
      },
      {
        id: "s3",
        title: "Essential Requirements",
        description: "Demonstration of conformity with SFDA IR-MDR essential requirements for safety and performance",
        fields: [
          { id: "3.1", label: "SFDA Essential Requirements Checklist", hint: "Clause-by-clause compliance matrix against SFDA IR-MDR Annex I General Safety and Performance Requirements with evidence references for each requirement", textarea: true },
          { id: "3.2", label: "Applied Standards", hint: "List of Saudi (SASO), ISO, IEC, and EN standards applied with full designation, edition, and statement of full or partial conformity", textarea: true },
          { id: "3.3", label: "Conformity Demonstration", hint: "Summary of methods used to demonstrate compliance with each essential requirement: testing, analysis, literature, equivalence, or clinical data with document references", textarea: true },
        ],
      },
      {
        id: "s4",
        title: "Risk Management",
        description: "Risk management documentation per ISO 14971 as required by SFDA IR-MDR",
        fields: [
          { id: "4.1", label: "Risk Management Plan (ISO 14971)", hint: "Risk management plan per ISO 14971:2019 defining scope, risk acceptability criteria, verification activities, and production/post-production information collection", textarea: true },
          { id: "4.2", label: "Hazard Identification", hint: "Systematic hazard identification using FMEA, FTA, or HAZOP covering all foreseeable hazards during normal use, reasonably foreseeable misuse, and fault conditions", textarea: true },
          { id: "4.3", label: "Risk Estimation & Evaluation", hint: "Risk estimation for each identified hazard with probability of occurrence and severity of harm, evaluated against defined acceptability criteria per ISO 14971 Annex C" },
          { id: "4.4", label: "Risk Control Measures", hint: "Risk control measures in priority order: inherently safe design, protective measures, and information for safety per ISO 14971 Clause 7", textarea: true },
          { id: "4.5", label: "Residual Risk Assessment", hint: "Evaluation of residual risks after control measures including overall residual risk acceptability and disclosure in labelling/IFU" },
          { id: "4.6", label: "Risk-Benefit Analysis", hint: "Overall benefit-risk determination demonstrating that residual risks are acceptable when weighed against intended clinical benefits per SFDA IR-MDR Annex I Chapter I", textarea: true },
        ],
      },
      {
        id: "s5",
        title: "Testing & Validation",
        description: "Verification and validation testing demonstrating device safety and performance",
        fields: [
          { id: "5.1", label: "Performance Testing", hint: "Design verification test reports demonstrating the device meets all design output specifications under nominal, worst-case, and simulated-use conditions", textarea: true },
          { id: "5.2", label: "Biocompatibility (ISO 10993)", hint: "Biological evaluation per ISO 10993-1:2018 with endpoint selection based on body contact nature and duration, including cytotoxicity, sensitization, and irritation", textarea: true },
          { id: "5.3", label: "Electrical Safety (IEC 60601)", hint: "IEC 60601-1 Ed. 3.2 test report with applicable particular standards (IEC 60601-2-XX) for electrically powered medical devices", textarea: true },
          { id: "5.4", label: "Electromagnetic Compatibility (EMC)", hint: "IEC 60601-1-2 Ed. 4.1 EMC test report covering immunity and emissions testing in the intended electromagnetic environment", textarea: true },
          { id: "5.5", label: "Software Validation (IEC 62304)", hint: "Software verification and validation per IEC 62304 including unit, integration, and system testing with traceability to software requirements", textarea: true },
          { id: "5.6", label: "Sterilization Validation", hint: "Validation of terminal sterilization per ISO 11135 (EtO), ISO 11137 (radiation), or ISO 17665 (moist heat) with sterility assurance demonstration", textarea: true },
          { id: "5.7", label: "Stability / Shelf Life", hint: "Real-time and accelerated aging studies per ASTM F1980 with sterile barrier system integrity testing per ISO 11607 throughout claimed shelf life", textarea: true },
          { id: "5.8", label: "Packaging Validation", hint: "Packaging validation per ISO 11607 including seal strength, distribution simulation (ASTM D4169), and transit stability testing" },
        ],
      },
      {
        id: "s6",
        title: "Clinical Evidence",
        description: "Clinical data supporting safety and performance per SFDA clinical evaluation requirements",
        fields: [
          { id: "6.1", label: "Clinical Evaluation Report", hint: "Systematic clinical evaluation per SFDA IR-MDR Annex XIV and MEDDEV 2.7/1 Rev 4 methodology demonstrating benefit-risk acceptability", textarea: true },
          { id: "6.2", label: "Clinical Data", hint: "Clinical investigation data per ISO 14155 (if conducted), including study design, endpoints, results, adverse events, and statistical analysis", textarea: true },
          { id: "6.3", label: "Literature Review", hint: "Structured literature search with defined databases, search strategy, PICO criteria, critical appraisal, and data synthesis supporting clinical claims", textarea: true },
          { id: "6.4", label: "Equivalence Analysis", hint: "Demonstration of clinical, technical, and biological equivalence to a predicate or equivalent device per SFDA IR-MDR Annex XIV Part A", textarea: true },
          { id: "6.5", label: "Post-Market Clinical Data", hint: "Post-market clinical follow-up (PMCF) plan and available post-market clinical data supporting ongoing safety and performance", textarea: true },
        ],
      },
      {
        id: "s7",
        title: "Quality System",
        description: "Quality management system documentation and SFDA establishment licensing",
        fields: [
          { id: "7.1", label: "ISO 13485 Certification", hint: "Current ISO 13485:2016 certificate with scope covering the device, issued by an IAF MLA signatory-accredited certification body" },
          { id: "7.2", label: "SFDA Establishment License", hint: "Valid SFDA medical device establishment license (MDEL) for the manufacturer, importer, and/or distributor with license number and scope" },
          { id: "7.3", label: "MDSAP Audit Report", hint: "Medical Device Single Audit Program (MDSAP) audit report if available, demonstrating QMS compliance across participating regulatory jurisdictions" },
          { id: "7.4", label: "QMS Audit Reports", hint: "Most recent QMS audit reports including internal audit summaries and third-party surveillance audit results with CAR closure status", textarea: true },
        ],
      },
      {
        id: "s8",
        title: "Labelling",
        description: "Bilingual labelling and instructions for use per SFDA requirements",
        fields: [
          { id: "8.1", label: "Arabic Labels", hint: "All device labels in Arabic per SFDA IR-MDR Annex I Chapter III labelling requirements including SFDA registration number and Arabic device name" },
          { id: "8.2", label: "English Labels", hint: "Device labels in English matching Arabic content with manufacturer name, model/catalogue number, lot/serial, and manufacturing/expiry dates" },
          { id: "8.3", label: "Instructions for Use (Bilingual)", hint: "Complete IFU in both Arabic and English per SFDA IR-MDR Annex I Section 23.4 with indications, contraindications, warnings, and operating instructions", textarea: true },
          { id: "8.4", label: "Packaging Labels", hint: "Inner and outer packaging labels in Arabic and English with storage conditions, sterility indicators, and SFDA-required symbols per ISO 15223-1" },
          { id: "8.5", label: "SFDA-Specific Labelling", hint: "SFDA-mandated labelling elements including SFDA logo usage requirements, marketing authorization number placement, and Arabic text formatting rules" },
          { id: "8.6", label: "UDI Labelling", hint: "UDI carrier (AIDC + HRI) on device and packaging per SFDA UDI requirements including GTIN format and production identifiers" },
        ],
      },
      {
        id: "s9",
        title: "Manufacturing",
        description: "Manufacturing site information, processes, and supply chain details",
        fields: [
          { id: "9.1", label: "Manufacturing Sites", hint: "Name, address, and SFDA status of all manufacturing, assembly, and sterilization sites with scope of activities at each location" },
          { id: "9.2", label: "Manufacturing Process Overview", hint: "Process flow from raw materials to finished device release including critical process steps, in-process controls, and validated processes", textarea: true },
          { id: "9.3", label: "Quality Control", hint: "Incoming, in-process, and final inspection/testing procedures with acceptance criteria, sampling plans, and measurement equipment calibration status" },
          { id: "9.4", label: "Key Suppliers", hint: "Critical component and raw material suppliers with qualification status, quality agreements, and supply chain risk management per ISO 13485 Clause 7.4" },
          { id: "9.5", label: "Sterilization Site", hint: "Contract sterilization facility name, address, ISO 11135/11137/17665 validation status, and quality agreement with routine dose/cycle monitoring" },
        ],
      },
      {
        id: "s10",
        title: "Post-Market & Certificates",
        description: "Post-market obligations, vigilance reporting, and supporting regulatory certificates",
        fields: [
          { id: "10.1", label: "Adverse Event Reporting to SFDA", hint: "Procedure for reporting serious incidents and field safety corrective actions to SFDA via the medical device vigilance system within mandated timelines (10/30 days)", textarea: true },
          { id: "10.2", label: "Field Safety Corrective Actions (FSCA)", hint: "FSCA procedures including field safety notice templates, distribution tracking, and SFDA notification requirements per IR-MDR Chapter 7" },
          { id: "10.3", label: "Recall Procedures", hint: "Device recall classification (Class I/II/III), recall initiation procedures, effectiveness checks, and SFDA recall notification process" },
          { id: "10.4", label: "Post-Market Surveillance Plan", hint: "Proactive PMS plan per SFDA IR-MDR Annex III including data sources, analysis methods, trend reporting, and periodic safety update reports", textarea: true },
          { id: "10.5", label: "CE Certificate (if applicable)", hint: "EC/EU certificate of conformity issued by a Notified Body under MDD 93/42/EEC or MDR 2017/745 if the device bears CE marking" },
          { id: "10.6", label: "Free Sale Certificate", hint: "Certificate of Free Sale from the country of origin confirming the device is legally marketed, apostilled or legalized for Saudi Arabia" },
          { id: "10.7", label: "Foreign Regulatory Approvals", hint: "Summary of marketing authorizations in reference jurisdictions (FDA, EU, Japan, Canada, Australia) with approval dates and indication scope" },
          { id: "10.8", label: "ISO 13485 Certificate", hint: "Current ISO 13485:2016 certificate copy with certification body accreditation details, scope statement, and validity dates" },
        ],
      },
    ],
  },
];
