import type { RegulatoryFramework } from "../types";

export const CN_FRAMEWORKS: RegulatoryFramework[] = [
  {
    id: "CN_NMPA_II", countryCode: "CN", countryName: "China", flag: "🇨🇳", authority: "NMPA", documentType: "Class II Registration", deviceType: "medical-device",
    sections: [
      { id: "admin", title: "Administrative Information", description: "Applicant, agent, and device identification", fields: [
        { id: "applicant", label: "Applicant Information", hint: "Manufacturer name, address, unified social credit code" },
        { id: "china_agent", label: "China Agent / MAH", hint: "Marketing Authorization Holder or designated agent in China with business license" },
        { id: "product_name_cn", label: "Product Name (Chinese)", hint: "Device name in Chinese conforming to NMPA naming conventions" },
        { id: "product_name_en", label: "Product Name (English)", hint: "Original device name in English as used internationally" },
        { id: "reg_cert_no", label: "Registration Certificate Number", hint: "Existing registration number if renewal or modification application" },
        { id: "device_listing", label: "Device Listing", hint: "NMPA classification catalogue code, subcategory, and product description code" },
      ]},
      { id: "ptr", title: "Product Technical Requirements", description: "Technical specifications and applicable standards", fields: [
        { id: "product_desc", label: "Product Description", hint: "Comprehensive description of the device including working principle and structural composition", textarea: true },
        { id: "model_specs", label: "Model and Specifications", hint: "All models, sizes, and configurations with distinguishing features", textarea: true },
        { id: "intended_use", label: "Intended Use", hint: "Specific clinical intended use including target population and clinical setting", textarea: true },
        { id: "classification", label: "Classification", hint: "Class II classification basis per NMPA Medical Device Classification Catalogue" },
        { id: "ptr_document", label: "Product Technical Requirements Document", hint: "Complete PTR per NMPA Order No.9 including performance indicators and test methods", textarea: true },
        { id: "cn_standards", label: "Applicable Chinese Standards (GB/YY)", hint: "All applicable mandatory GB and recommended YY standards with edition numbers", textarea: true },
      ]},
      { id: "research", title: "Research Data", description: "Product development and non-clinical testing", fields: [
        { id: "product_dev", label: "Product Development", hint: "Design and development history including design inputs, outputs, and verification", textarea: true },
        { id: "literature", label: "Literature Review", hint: "Published literature supporting safety and effectiveness of the device", textarea: true },
        { id: "nonclinical", label: "Non-Clinical Testing", hint: "Summary of all bench testing, animal studies, and simulated-use testing", textarea: true },
        { id: "biocompat", label: "Biocompatibility (GB/T 16886)", hint: "Biological evaluation per GB/T 16886 series (equivalent to ISO 10993) with test reports", textarea: true },
        { id: "electrical_safety", label: "Electrical Safety (GB 9706)", hint: "Electrical safety testing per GB 9706.1 and applicable particular standards", textarea: true },
        { id: "emc", label: "Electromagnetic Compatibility", hint: "EMC testing per GB/T applicable standards (YY 0505 or GB 4824 series)", textarea: true },
        { id: "software", label: "Software (YY/T 0664)", hint: "Software description and lifecycle documentation per YY/T 0664 (IEC 62304)", textarea: true },
        { id: "sterilization", label: "Sterilization", hint: "Sterilization method validation per applicable GB standards (GB 18280/18281/18278)", textarea: true },
        { id: "stability", label: "Stability / Shelf Life", hint: "Accelerated and real-time aging studies demonstrating claimed shelf life", textarea: true },
        { id: "packaging", label: "Packaging Validation", hint: "Transport simulation and package integrity testing per GB/T or ASTM equivalent", textarea: true },
      ]},
      { id: "clinical", title: "Clinical Evaluation", description: "Clinical evidence for safety and effectiveness", fields: [
        { id: "clinical_eval", label: "Clinical Evaluation Report", hint: "Clinical evaluation per NMPA Guideline No.14 for medical device clinical evaluation", textarea: true },
        { id: "clinical_trial", label: "Clinical Trial Data", hint: "Clinical trial data if required per NMPA exempt list determination", textarea: true },
        { id: "comparator", label: "Comparator Device Analysis", hint: "Comparison with legally marketed equivalent device in China", textarea: true },
      ]},
      { id: "mfg", title: "Manufacturing", description: "Quality management and production information", fields: [
        { id: "qms", label: "QMS (YY/T 0287)", hint: "Quality management system documentation per YY/T 0287 (ISO 13485)", textarea: true },
        { id: "process", label: "Production Process", hint: "Manufacturing process flow including critical control points and in-process testing", textarea: true },
        { id: "site_info", label: "Manufacturing Site Information", hint: "Facility name, address, scope of manufacturing, and NMPA site registration", textarea: true },
        { id: "suppliers", label: "Key Suppliers", hint: "Critical component and material suppliers with qualification evidence", textarea: true },
        { id: "special_processes", label: "Special Processes", hint: "Processes requiring validation (sterilization, welding, sealing) with validation status", textarea: true },
        { id: "process_validation", label: "Process Validation", hint: "Validation protocols and reports for all special and critical processes", textarea: true },
      ]},
      { id: "labeling", title: "Labelling", description: "Chinese language labelling and instructions", fields: [
        { id: "labels_cn", label: "Chinese Labels", hint: "All labels in Chinese per NMPA labelling requirements and GB/T standards", textarea: true },
        { id: "ifu_cn", label: "IFU in Chinese", hint: "Instructions for use in Chinese per YY/T 0466 (ISO 15223) symbol requirements", textarea: true },
        { id: "packaging_labels", label: "Packaging Labels", hint: "Primary, secondary, and shipping package labelling in Chinese", textarea: true },
        { id: "udi_di", label: "UDI-DI", hint: "Unique Device Identifier per NMPA UDI implementation requirements" },
      ]},
      { id: "risk", title: "Risk Management", description: "Risk management per YY/T 0316", fields: [
        { id: "risk_mgmt", label: "Risk Management (YY/T 0316)", hint: "Complete risk management file per YY/T 0316 (ISO 14971) including plan, analysis, and report", textarea: true },
        { id: "hazard_id", label: "Hazard Identification", hint: "Systematic hazard identification using FMEA, FTA, or HAZOP methods", textarea: true },
        { id: "risk_control", label: "Risk Control", hint: "Risk control measures implemented and verification of effectiveness", textarea: true },
      ]},
      { id: "postmarket", title: "Post-Market Requirements", description: "Surveillance, adverse events, and recall management", fields: [
        { id: "adverse_monitoring", label: "Adverse Event Monitoring", hint: "Adverse event monitoring and reporting plan per NMPA Order No.1 (2020)", textarea: true },
        { id: "reevaluation", label: "Re-evaluation", hint: "Product re-evaluation plan for ongoing safety and effectiveness assessment", textarea: true },
        { id: "recall_mgmt", label: "Recall Management", hint: "Recall classification and procedures per NMPA medical device recall regulations", textarea: true },
      ]},
      { id: "certs", title: "Certificates", description: "Required regulatory certificates and test reports", fields: [
        { id: "type_test", label: "Type Testing Report", hint: "Test report from NMPA-accredited testing institution (e.g. CMDE-designated lab)" },
        { id: "free_sale", label: "Free Sale Certificate", hint: "Certificate of free sale from country of origin regulatory authority" },
        { id: "iso_13485", label: "ISO 13485 Certificate", hint: "Current ISO 13485 QMS certificate from accredited certification body" },
        { id: "gmp_cert", label: "GMP Certificate", hint: "Manufacturing facility GMP certificate from country of origin regulatory authority" },
        { id: "business_license", label: "Business License", hint: "Valid business license of the applicant and China agent" },
      ]},
      { id: "cn_specific", title: "Country-Specific Requirements", description: "NMPA-specific regulatory requirements for China", fields: [
        { id: "product_standard", label: "NMPA Product Standard (YY Code)", hint: "Applicable YY industry standard number and compliance declaration" },
        { id: "cn_clinical_req", label: "Chinese Clinical Trial Requirements", hint: "Clinical trial waiver justification or CDE clinical trial approval documentation" },
        { id: "reg_testing", label: "Registration Testing Requirements", hint: "Registration testing scope per NMPA-designated lab requirements with sample information" },
        { id: "cn_declaration", label: "Self-Declaration of Conformity", hint: "Manufacturer's declaration of product conformity to Chinese regulatory requirements" },
        { id: "power_of_attorney", label: "Power of Attorney", hint: "Notarized and legalized power of attorney from manufacturer to China agent" },
        { id: "sales_cert_legalized", label: "Legalized Sales Certificate", hint: "Free sale certificate notarized and legalized by Chinese embassy in country of origin" },
        { id: "cn_insurance", label: "Product Liability Insurance", hint: "Product liability insurance covering distribution in the Chinese market" },
        { id: "technical_review", label: "CMDE Technical Review Request", hint: "Center for Medical Device Evaluation technical review application with fee payment receipt" },
      ]},
    ],
  },
  {
    id: "CN_NMPA_III", countryCode: "CN", countryName: "China", flag: "🇨🇳", authority: "NMPA", documentType: "Class III Registration", deviceType: "medical-device",
    sections: [
      { id: "admin", title: "Administrative Information", description: "Applicant, agent, and device identification", fields: [
        { id: "applicant", label: "Applicant Information", hint: "Manufacturer name, address, unified social credit code, and legal representative" },
        { id: "china_agent", label: "China Agent / MAH", hint: "Marketing Authorization Holder in China with valid business license and MDEL" },
        { id: "product_name_cn", label: "Product Name (Chinese)", hint: "Device name in Chinese per NMPA medical device naming conventions" },
        { id: "product_name_en", label: "Product Name (English)", hint: "Original device name in English" },
        { id: "reg_cert_no", label: "Registration Certificate Number", hint: "Previous registration certificate number for renewal/modification" },
        { id: "device_listing", label: "Device Listing", hint: "Class III classification catalogue code and subcategory per NMPA classification rules" },
        { id: "innovative_device", label: "Innovative Device Pathway", hint: "Innovative medical device special review application status per NMPA Channel" },
      ]},
      { id: "ptr", title: "Product Technical Requirements", description: "Technical specifications and applicable standards", fields: [
        { id: "product_desc", label: "Product Description", hint: "Comprehensive description including working principle, structural composition, and key components", textarea: true },
        { id: "model_specs", label: "Model and Specifications", hint: "All models, sizes, configurations with detailed distinguishing technical parameters", textarea: true },
        { id: "intended_use", label: "Intended Use", hint: "Specific clinical intended use, target patient population, and clinical setting", textarea: true },
        { id: "classification", label: "Classification", hint: "Class III classification basis per NMPA Medical Device Classification Catalogue with rationale" },
        { id: "ptr_document", label: "Product Technical Requirements Document", hint: "Complete PTR per NMPA Order No.9 with all performance indicators and test methods", textarea: true },
        { id: "cn_standards", label: "Applicable Chinese Standards (GB/YY)", hint: "All applicable mandatory (GB) and recommended (YY) standards with current editions", textarea: true },
        { id: "priority_review", label: "Priority Review Application", hint: "Priority review qualification documentation if applicable per NMPA provisions", textarea: true },
      ]},
      { id: "research", title: "Research Data", description: "Comprehensive product development and non-clinical evidence", fields: [
        { id: "product_dev", label: "Product Development", hint: "Complete design and development documentation including design history file", textarea: true },
        { id: "literature", label: "Literature Review", hint: "Systematic literature review of scientific publications supporting the device", textarea: true },
        { id: "nonclinical", label: "Non-Clinical Testing", hint: "All bench testing, animal studies, computational modeling, and simulated-use testing", textarea: true },
        { id: "biocompat", label: "Biocompatibility (GB/T 16886)", hint: "Comprehensive biological evaluation per GB/T 16886 series with complete test reports", textarea: true },
        { id: "electrical_safety", label: "Electrical Safety (GB 9706)", hint: "Complete electrical safety testing per GB 9706.1 and all applicable particular standards", textarea: true },
        { id: "emc", label: "Electromagnetic Compatibility", hint: "EMC testing per applicable GB standards with emissions and immunity results", textarea: true },
        { id: "software", label: "Software (YY/T 0664)", hint: "Full software documentation per YY/T 0664 including architecture, hazard analysis, and cybersecurity", textarea: true },
        { id: "sterilization", label: "Sterilization Validation", hint: "Complete sterilization validation per GB 18280/18281/18278 with bioburden and SAL data", textarea: true },
        { id: "stability", label: "Stability / Shelf Life", hint: "Accelerated and real-time aging per applicable standards with statistical analysis", textarea: true },
        { id: "packaging", label: "Packaging Validation", hint: "Package integrity and transport testing per applicable Chinese and international standards", textarea: true },
        { id: "animal_studies", label: "Animal Studies", hint: "Preclinical animal study protocols, results, and conclusions for implantable or high-risk devices", textarea: true },
        { id: "material_char", label: "Material Characterization", hint: "Complete chemical and physical characterization of materials per GB/T 16886-18/19/20", textarea: true },
      ]},
      { id: "clinical", title: "Clinical Evaluation", description: "Mandatory clinical data for Class III devices", fields: [
        { id: "clinical_eval", label: "Clinical Evaluation Report", hint: "Comprehensive clinical evaluation per NMPA Guideline No.14", textarea: true },
        { id: "clinical_trial", label: "Clinical Trial Data (Mandatory)", hint: "Clinical trial report per NMPA GCP with protocol, statistical analysis, and results", textarea: true },
        { id: "clinical_protocol", label: "Clinical Trial Protocol", hint: "CDE-approved clinical trial protocol with endpoints, sample size justification", textarea: true },
        { id: "statistical_analysis", label: "Statistical Analysis Plan", hint: "Pre-specified statistical analysis plan and independent statistical report", textarea: true },
        { id: "comparator", label: "Comparator Device Analysis", hint: "Detailed equivalence analysis with legally marketed Class III device in China", textarea: true },
        { id: "multi_center", label: "Multi-Center Trial Data", hint: "Multi-center clinical trial data from NMPA-approved clinical trial sites", textarea: true },
      ]},
      { id: "mfg", title: "Manufacturing", description: "Quality management and production information", fields: [
        { id: "qms", label: "QMS (YY/T 0287)", hint: "Quality management system per YY/T 0287 with detailed process documentation", textarea: true },
        { id: "process", label: "Production Process", hint: "Complete manufacturing process flow with critical control points and process parameters", textarea: true },
        { id: "site_info", label: "Manufacturing Site Information", hint: "All facility details including cleanroom classifications and NMPA site registration", textarea: true },
        { id: "suppliers", label: "Key Suppliers", hint: "Critical component suppliers with qualification, audits, and quality agreements", textarea: true },
        { id: "special_processes", label: "Special Processes", hint: "All processes requiring validation with current validation status and revalidation schedule", textarea: true },
        { id: "process_validation", label: "Process Validation", hint: "IQ/OQ/PQ protocols and reports for all validated processes", textarea: true },
      ]},
      { id: "labeling", title: "Labelling", description: "Chinese language labelling and instructions", fields: [
        { id: "labels_cn", label: "Chinese Labels", hint: "All labels in simplified Chinese per NMPA labelling regulations", textarea: true },
        { id: "ifu_cn", label: "IFU in Chinese", hint: "Complete instructions for use in Chinese per YY/T 0466 requirements", textarea: true },
        { id: "packaging_labels", label: "Packaging Labels", hint: "All packaging labelling including barcodes and UDI in Chinese", textarea: true },
        { id: "udi_di", label: "UDI-DI", hint: "Unique Device Identifier per NMPA UDI system with GUDI database submission" },
      ]},
      { id: "risk", title: "Risk Management", description: "Comprehensive risk management per YY/T 0316", fields: [
        { id: "risk_mgmt", label: "Risk Management (YY/T 0316)", hint: "Complete risk management file per YY/T 0316 (ISO 14971)", textarea: true },
        { id: "hazard_id", label: "Hazard Identification", hint: "Systematic hazard identification using FMEA, FTA, HAZOP for all hazard categories", textarea: true },
        { id: "risk_control", label: "Risk Control Measures", hint: "Three-tier risk control: inherent safety design, protective measures, information for safety", textarea: true },
        { id: "residual_risk", label: "Residual Risk Evaluation", hint: "Overall residual risk acceptability and benefit-risk determination", textarea: true },
      ]},
      { id: "postmarket", title: "Post-Market Requirements", description: "Surveillance, adverse events, and recall management", fields: [
        { id: "adverse_monitoring", label: "Adverse Event Monitoring", hint: "Adverse event monitoring and reporting per NMPA Order No.1 (2020) for Class III", textarea: true },
        { id: "periodic_report", label: "Periodic Safety Update Report", hint: "Annual safety report requirements for Class III devices", textarea: true },
        { id: "reevaluation", label: "Re-evaluation Plan", hint: "Product re-evaluation plan per NMPA lifecycle requirements", textarea: true },
        { id: "recall_mgmt", label: "Recall Management", hint: "Recall procedures per NMPA medical device recall management regulations", textarea: true },
      ]},
      { id: "certs", title: "Certificates", description: "Required regulatory certificates and test reports", fields: [
        { id: "type_test", label: "Type Testing Report", hint: "Complete test report from NMPA-accredited testing institution covering all PTR items" },
        { id: "free_sale", label: "Free Sale Certificate", hint: "Certificate of free sale from country of origin legalized by Chinese embassy" },
        { id: "iso_13485", label: "ISO 13485 Certificate", hint: "Current ISO 13485 certificate from IAF-accredited certification body" },
        { id: "gmp_cert", label: "GMP Certificate", hint: "Manufacturing facility GMP certificate from country of origin regulatory authority" },
      ]},
      { id: "cn_specific", title: "Country-Specific Requirements", description: "NMPA-specific regulatory requirements for Class III", fields: [
        { id: "product_standard", label: "NMPA Product Standard (YY Code)", hint: "Applicable YY industry standards with mandatory compliance declaration" },
        { id: "cn_clinical_req", label: "Chinese Clinical Trial Requirements", hint: "CDE clinical trial approval (IDE equivalent) and trial site qualifications" },
        { id: "reg_testing", label: "Registration Testing Requirements", hint: "Registration testing at NMPA-designated laboratory with full PTR test scope" },
        { id: "innovative_pathway", label: "Innovative Device Pathway Documentation", hint: "Special review documentation if device qualifies as innovative under NMPA provisions" },
        { id: "expert_review", label: "Expert Review Panel", hint: "Technical review expert panel documentation and pre-submission meeting records" },
        { id: "cn_declaration_iii", label: "Self-Declaration of Conformity", hint: "Manufacturer's declaration of product conformity for Class III device" },
        { id: "power_of_attorney", label: "Power of Attorney", hint: "Notarized and legalized power of attorney from manufacturer to China MAH" },
        { id: "sales_cert_legalized", label: "Legalized Sales Certificate", hint: "Free sale certificate notarized and legalized by Chinese embassy" },
        { id: "cn_insurance", label: "Product Liability Insurance", hint: "Product liability insurance covering the Chinese market for high-risk devices" },
        { id: "technical_review", label: "CMDE Technical Review Request", hint: "CDE pre-submission consultation and technical review application documentation" },
        { id: "annual_report", label: "Annual Quality Report", hint: "Annual product quality tracking report requirements for Class III devices" },
      ]},
    ],
  },
  {
    id: "CN_NMPA_IVD", countryCode: "CN", countryName: "China", flag: "🇨🇳", authority: "NMPA", documentType: "IVD Registration", deviceType: "ivd",
    sections: [
      { id: "admin", title: "Administrative Information", description: "Applicant, agent, and IVD device identification", fields: [
        { id: "applicant", label: "Applicant Information", hint: "IVD manufacturer name, address, and unified social credit code" },
        { id: "china_agent", label: "China Agent / MAH", hint: "Marketing Authorization Holder or designated agent in China for IVD products" },
        { id: "product_name_cn", label: "Product Name (Chinese)", hint: "IVD reagent or instrument name in Chinese per NMPA IVD naming rules" },
        { id: "product_name_en", label: "Product Name (English)", hint: "Original IVD product name in English" },
        { id: "reg_cert_no", label: "Registration Certificate Number", hint: "Existing IVD registration number for renewal or modification" },
        { id: "device_listing", label: "IVD Classification", hint: "IVD classification per NMPA IVD Classification Catalogue (Class I/II/III)" },
      ]},
      { id: "ptr", title: "Product Technical Requirements", description: "IVD technical specifications and standards", fields: [
        { id: "product_desc", label: "Product Description", hint: "IVD reagent composition, assay principle, and intended analyte detection", textarea: true },
        { id: "model_specs", label: "Reagent Specifications", hint: "Pack sizes, configurations, and component specifications", textarea: true },
        { id: "intended_use", label: "Intended Use", hint: "Specific analyte, specimen type, testing population, and clinical application", textarea: true },
        { id: "classification", label: "IVD Classification", hint: "Class I/II/III per NMPA IVD classification rules with rationale" },
        { id: "ptr_document", label: "Product Technical Requirements Document", hint: "Complete IVD PTR with performance indicators, acceptance criteria, and test methods", textarea: true },
        { id: "cn_standards", label: "Applicable Chinese Standards (GB/YY)", hint: "GB and YY standards for IVD including YY/T 1579, YY/T 0316, applicable analyte-specific standards", textarea: true },
      ]},
      { id: "research", title: "Research Data", description: "IVD product development and analytical studies", fields: [
        { id: "product_dev", label: "Product Development", hint: "IVD design and development including reagent formulation and optimization", textarea: true },
        { id: "literature", label: "Literature Review", hint: "Scientific literature supporting the analytical and clinical performance claims", textarea: true },
        { id: "raw_materials", label: "Raw Material Studies", hint: "Key raw material (antibodies, antigens, enzymes) characterization and qualification", textarea: true },
        { id: "ref_materials", label: "Reference Materials", hint: "Calibration traceability, reference standards, and control materials with sources", textarea: true },
        { id: "stability", label: "Stability Studies", hint: "Real-time, accelerated, open-vial, on-board, and shipping stability data", textarea: true },
        { id: "packaging", label: "Packaging Validation", hint: "Packaging integrity testing and transport simulation results", textarea: true },
      ]},
      { id: "analytical", title: "Analytical Performance", description: "Complete analytical performance evaluation", fields: [
        { id: "sensitivity", label: "Analytical Sensitivity (LoB/LoD/LoQ)", hint: "Limit of blank, limit of detection, and limit of quantitation per CLSI EP17", textarea: true },
        { id: "specificity", label: "Analytical Specificity", hint: "Cross-reactivity and interference testing with common substances", textarea: true },
        { id: "accuracy", label: "Accuracy / Trueness", hint: "Method comparison, recovery studies, and reference material testing", textarea: true },
        { id: "precision", label: "Precision / Reproducibility", hint: "Repeatability, within-lab, and between-lab reproducibility per CLSI EP05/EP15", textarea: true },
        { id: "lod", label: "Detection Capability", hint: "Diagnostic sensitivity and specificity with clinical samples", textarea: true },
        { id: "ref_range", label: "Reference Range / Cut-off", hint: "Reference interval establishment or cut-off determination with Chinese population data", textarea: true },
        { id: "interfering", label: "Interfering Substances", hint: "Endogenous and exogenous interference testing per CLSI EP07", textarea: true },
        { id: "hook_effect", label: "Hook Effect", hint: "High-dose hook effect evaluation for immunoassays", textarea: true },
        { id: "measuring_range", label: "Measuring Range / Linearity", hint: "Analytical measuring interval and linearity verification per CLSI EP06", textarea: true },
      ]},
      { id: "specimen", title: "Specimen Requirements", description: "Specimen collection, handling, and stability", fields: [
        { id: "specimen_types", label: "Specimen Types", hint: "All validated specimen matrices (serum, plasma, whole blood, urine, etc.)", textarea: true },
        { id: "collection", label: "Collection Requirements", hint: "Collection device, anticoagulant, volume, and handling instructions", textarea: true },
        { id: "specimen_stability", label: "Specimen Stability", hint: "Stability under various storage conditions (room temp, refrigerated, frozen)", textarea: true },
        { id: "matrix_comparison", label: "Matrix Comparison", hint: "Equivalence studies between different specimen matrices", textarea: true },
      ]},
      { id: "clinical", title: "Clinical Evaluation", description: "Clinical performance evaluation", fields: [
        { id: "clinical_eval", label: "Clinical Evaluation Report", hint: "Clinical performance evaluation per NMPA IVD clinical evaluation guidelines", textarea: true },
        { id: "clinical_trial", label: "Clinical Trial Data", hint: "Multi-center clinical trial with Chinese clinical sites if required", textarea: true },
        { id: "comparator", label: "Comparator Method", hint: "Method comparison with reference method or legally marketed IVD in China", textarea: true },
        { id: "clinical_sensitivity", label: "Clinical Sensitivity/Specificity", hint: "Diagnostic sensitivity and specificity with confirmed clinical samples", textarea: true },
      ]},
      { id: "mfg", title: "Manufacturing", description: "Quality management and IVD production", fields: [
        { id: "qms", label: "QMS (YY/T 0287)", hint: "Quality management system per YY/T 0287 for IVD manufacturing", textarea: true },
        { id: "process", label: "Production Process", hint: "IVD reagent manufacturing process including formulation, filling, and lyophilization", textarea: true },
        { id: "site_info", label: "Manufacturing Site Information", hint: "Facility details including cleanroom classification and NMPA site registration", textarea: true },
        { id: "process_validation", label: "Process Validation", hint: "Validation of critical IVD manufacturing processes", textarea: true },
      ]},
      { id: "labeling", title: "Labelling", description: "Chinese language IVD labelling", fields: [
        { id: "labels_cn", label: "Chinese Labels", hint: "IVD reagent labels in Chinese per NMPA IVD labelling requirements", textarea: true },
        { id: "ifu_cn", label: "IFU in Chinese", hint: "IVD instructions for use in Chinese including assay procedure and result interpretation", textarea: true },
        { id: "packaging_labels", label: "Packaging Labels", hint: "Primary (vial), secondary (kit box), and shipping labels in Chinese", textarea: true },
        { id: "udi_di", label: "UDI-DI", hint: "Unique Device Identifier for IVD per NMPA UDI system requirements" },
      ]},
      { id: "risk", title: "Risk Management", description: "Risk management per YY/T 0316", fields: [
        { id: "risk_mgmt", label: "Risk Management (YY/T 0316)", hint: "Risk management file per YY/T 0316 for IVD-specific hazards", textarea: true },
        { id: "hazard_id", label: "Hazard Identification", hint: "IVD-specific hazards: false results, specimen handling, reagent hazards", textarea: true },
        { id: "risk_control", label: "Risk Control", hint: "Risk control measures for analytical and clinical performance risks", textarea: true },
      ]},
      { id: "certs", title: "Certificates", description: "Required certificates and test reports", fields: [
        { id: "type_test", label: "Type Testing Report", hint: "IVD registration testing report from NMPA-accredited laboratory" },
        { id: "free_sale", label: "Free Sale Certificate", hint: "Certificate of free sale from country of origin" },
        { id: "iso_13485", label: "ISO 13485 Certificate", hint: "ISO 13485 QMS certificate covering IVD manufacturing scope" },
      ]},
      { id: "cn_specific", title: "Country-Specific Requirements", description: "NMPA-specific IVD regulatory requirements", fields: [
        { id: "product_standard", label: "NMPA Product Standard (YY Code)", hint: "Applicable YY standards for the specific IVD analyte or technology platform" },
        { id: "cn_clinical_req", label: "Chinese Clinical Requirements", hint: "IVD clinical trial requirements including Chinese population sample requirements" },
        { id: "reg_testing", label: "Registration Testing", hint: "IVD registration testing scope at NMPA-designated laboratory" },
        { id: "reference_materials_cn", label: "Chinese Reference Materials", hint: "National reference materials or standards from NIFDC if applicable" },
        { id: "cn_declaration_ivd", label: "Self-Declaration of Conformity", hint: "Manufacturer's declaration of IVD product conformity to Chinese regulations" },
        { id: "power_of_attorney", label: "Power of Attorney", hint: "Notarized and legalized power of attorney from manufacturer to China agent" },
        { id: "sales_cert_legalized", label: "Legalized Sales Certificate", hint: "Free sale certificate legalized by Chinese embassy for IVD products" },
        { id: "cn_insurance", label: "Product Liability Insurance", hint: "Product liability insurance covering IVD distribution in China" },
        { id: "technical_review_ivd", label: "CMDE Technical Review Request", hint: "IVD-specific CMDE technical review application and pre-submission documentation" },
        { id: "nifdc_samples", label: "NIFDC Sample Submission", hint: "National reference sample submission to NIFDC for IVD products requiring national lot release" },
        { id: "ivd_panel", label: "Clinical Sample Panel", hint: "Chinese clinical sample panel requirements including positive/negative confirmed samples" },
      ]},
    ],
  },
];
