import type { RegulatoryFramework } from "../types";

export const JP_FRAMEWORKS: RegulatoryFramework[] = [
  {
    id: "JP_SHONIN", countryCode: "JP", countryName: "Japan", flag: "🇯🇵", authority: "PMDA/MHLW", documentType: "Shonin (Approval) Application",
    sections: [
      { id: "admin", title: "Administrative Information", description: "MAH, DMAH, and device identification", fields: [
        { id: "mah", label: "Marketing Authorization Holder (MAH)", hint: "Japanese MAH name, address, and PMDA registration number" },
        { id: "dmah", label: "Designated Marketing Authorization Holder (DMAH)", hint: "Foreign manufacturer's designated MAH in Japan with valid license" },
        { id: "managing_director", label: "Designated Managing Director", hint: "Person responsible for post-market safety management in Japan" },
        { id: "device_name_generic", label: "Device Name (Generic)", hint: "MHLW-recognized generic name per Japanese device nomenclature" },
        { id: "device_name_brand", label: "Device Name (Brand)", hint: "Commercial brand name and model numbers for the Japanese market" },
        { id: "classification", label: "Classification (Specially Controlled)", hint: "Class III or IV specially controlled medical device per MHLW Ministerial Ordinance" },
      ]},
      { id: "sted", title: "STED (Summary Technical Documentation)", description: "Comprehensive device summary per GHTF/IMDRF STED format", fields: [
        { id: "device_desc", label: "Device Description", hint: "Comprehensive description of device including principles of operation and key features", textarea: true },
        { id: "intended_use", label: "Intended Use / Indications", hint: "Intended purpose, target patient population, and specific clinical indications", textarea: true },
        { id: "principles", label: "Principles of Operation", hint: "Scientific and engineering principles, mode of action, and energy source", textarea: true },
        { id: "design", label: "Design Description", hint: "Design characteristics, materials, dimensions, and engineering drawings", textarea: true },
        { id: "manufacturing", label: "Manufacturing Summary", hint: "Manufacturing process overview and critical process parameters", textarea: true },
        { id: "risk_summary", label: "Risk Management Summary", hint: "Summary of risk management process and residual risk acceptability", textarea: true },
        { id: "clinical_summary", label: "Clinical Evidence Summary", hint: "Summary of clinical data supporting safety and efficacy", textarea: true },
        { id: "labeling_summary", label: "Labelling Summary", hint: "Overview of proposed labelling content for Japanese market", textarea: true },
      ]},
      { id: "performance", title: "Performance & Safety Testing", description: "Testing per JIS standards and international equivalents", fields: [
        { id: "jis_standards", label: "JIS Standards Compliance", hint: "All applicable JIS (Japanese Industrial Standards) with test results and conformity", textarea: true },
        { id: "performance_testing", label: "Performance Testing", hint: "Complete bench testing data demonstrating device performance claims", textarea: true },
        { id: "biocompat", label: "Biocompatibility", hint: "Biological evaluation per JIS T 0993 (ISO 10993) with complete test reports", textarea: true },
        { id: "electrical_safety", label: "Electrical Safety (JIS T 0601)", hint: "Electrical safety testing per JIS T 0601-1 and applicable particular standards", textarea: true },
        { id: "emc", label: "EMC Testing", hint: "Electromagnetic compatibility per JIS T 0601-1-2 or equivalent", textarea: true },
        { id: "sterilization", label: "Sterilization Validation", hint: "Sterilization process validation per applicable JIS/ISO standards", textarea: true },
        { id: "stability", label: "Stability / Shelf Life", hint: "Stability testing supporting claimed shelf life with Japanese storage conditions", textarea: true },
        { id: "software", label: "Software Documentation", hint: "Software lifecycle documentation per JIS T 2304 (IEC 62304) and cybersecurity", textarea: true },
      ]},
      { id: "clinical", title: "Clinical Data", description: "Clinical trial data per Japanese GCP", fields: [
        { id: "clinical_trial", label: "Clinical Trial Data", hint: "Clinical trial conducted per Japanese GCP (MHLW Ordinance No.36) with full report", textarea: true },
        { id: "clinical_eval", label: "Clinical Evaluation", hint: "Systematic clinical evaluation of all available clinical evidence", textarea: true },
        { id: "foreign_data", label: "Foreign Clinical Data Acceptance", hint: "Justification for acceptance of foreign clinical data per MHLW notification (ethnic factors)", textarea: true },
        { id: "pmcf_data", label: "Post-Market Clinical Follow-up", hint: "Post-market clinical data from approved markets if available", textarea: true },
      ]},
      { id: "qms", title: "QMS Compliance", description: "Quality management system per QMS Ordinance", fields: [
        { id: "qms_169", label: "QMS Ordinance 169 Compliance", hint: "Compliance with MHLW QMS Ordinance No.169 (Japanese QMS regulation)", textarea: true },
        { id: "qms_audit", label: "QMS Audit", hint: "PMDA QMS conformity audit results or third-party audit certificate" },
        { id: "iso_13485", label: "ISO 13485 Certification", hint: "Current ISO 13485 certificate covering product scope from accredited body" },
      ]},
      { id: "risk", title: "Risk Management", description: "Risk management per ISO 14971 / JIS T 14971", fields: [
        { id: "risk_plan", label: "Risk Management per ISO 14971", hint: "Risk management plan and process per JIS T 14971 (ISO 14971)", textarea: true },
        { id: "fta", label: "Fault Tree Analysis", hint: "Top-down deductive failure analysis for critical safety hazards", textarea: true },
        { id: "fmea", label: "FMEA", hint: "Failure mode and effects analysis for device components and processes", textarea: true },
      ]},
      { id: "mfg", title: "Manufacturing Information", description: "Manufacturing sites, processes, and quality control", fields: [
        { id: "mfg_sites", label: "Manufacturing Sites", hint: "All manufacturing, sterilization, and final release sites with addresses and scope", textarea: true },
        { id: "process_overview", label: "Process Overview", hint: "Manufacturing process flow from raw materials to finished product", textarea: true },
        { id: "quality_control", label: "Quality Control", hint: "In-process and final inspection test methods and acceptance criteria", textarea: true },
        { id: "inspection", label: "Inspection Procedures", hint: "Incoming, in-process, and final product inspection procedures", textarea: true },
      ]},
      { id: "labeling", title: "Labelling", description: "Japanese language labelling requirements", fields: [
        { id: "labels_jp", label: "Japanese Labels", hint: "All labels in Japanese per PAL (Pharmaceutical Affairs Law) requirements", textarea: true },
        { id: "ifu_jp", label: "IFU in Japanese", hint: "Complete instructions for use in Japanese per MHLW labelling standards", textarea: true },
        { id: "packaging", label: "Packaging", hint: "Primary and secondary packaging with Japanese text and regulatory symbols", textarea: true },
        { id: "classified_labels", label: "Classified Label Requirements", hint: "Class-specific labelling requirements per MHLW classification guidelines" },
      ]},
      { id: "postmarket", title: "Post-Market Safety Measures", description: "Post-market surveillance and reporting", fields: [
        { id: "safety_measures", label: "Post-Market Safety Measures", hint: "Safety management plan per MHLW GVP (Good Vigilance Practice) ordinance", textarea: true },
        { id: "adverse_reporting", label: "Adverse Event Reporting to PMDA", hint: "Adverse event reporting procedures and timelines per PAL requirements", textarea: true },
        { id: "reexamination", label: "Re-examination", hint: "Re-examination period and plan for new medical devices (typically 3-7 years)", textarea: true },
        { id: "reevaluation", label: "Re-evaluation", hint: "Re-evaluation requirements when safety/efficacy concerns arise post-market", textarea: true },
      ]},
      { id: "certs", title: "Certificates & Consultations", description: "PMDA consultations and foreign approvals", fields: [
        { id: "pmda_consultation", label: "PMDA Consultation Record", hint: "Records of pre-submission consultations with PMDA review division" },
        { id: "foreign_approvals", label: "Foreign Regulatory Approvals", hint: "Approval status in US (FDA), EU (CE), and other major markets", textarea: true },
        { id: "iso_13485_orig", label: "ISO 13485 Certificate (Original)", hint: "Original ISO 13485 certificate from accredited body covering the product scope" },
        { id: "free_sale", label: "Free Sale Certificate", hint: "Certificate of free sale from country of origin regulatory authority" },
      ]},
      { id: "jp_specific", title: "Country-Specific Requirements", description: "Japan-specific regulatory documentation", fields: [
        { id: "pharmacopoeia", label: "Japanese Pharmacopoeia References", hint: "Applicable JP (Japanese Pharmacopoeia) monograph references for materials" },
        { id: "pre_submission", label: "PMDA Pre-Submission Meeting Records", hint: "Pre-application consultation meeting minutes and PMDA guidance received", textarea: true },
        { id: "ctn", label: "Clinical Trial Notification (CTN)", hint: "CTN submitted to PMDA for Japanese clinical trial with acceptance documentation" },
        { id: "accredited_foreign_mfr", label: "Accredited Foreign Manufacturer", hint: "MHLW foreign manufacturer accreditation (Gaikoku Seizogyo-sha Ninsho)" },
        { id: "jis_declaration", label: "JIS Conformity Declaration", hint: "Declaration of conformity to all applicable JIS standards", textarea: true },
        { id: "mhlw_fee", label: "MHLW Application Fee Receipt", hint: "Revenue stamp or application fee payment receipt for Shonin application" },
      ]},
    ],
  },
  {
    id: "JP_CERTIFICATION", countryCode: "JP", countryName: "Japan", flag: "🇯🇵", authority: "PMDA/MHLW", documentType: "Certification Application",
    sections: [
      { id: "admin", title: "Administrative Information", description: "MAH, DMAH, and device identification", fields: [
        { id: "mah", label: "Marketing Authorization Holder (MAH)", hint: "Japanese MAH name, address, and license number" },
        { id: "dmah", label: "Designated Marketing Authorization Holder (DMAH)", hint: "Foreign manufacturer's designated MAH in Japan" },
        { id: "managing_director", label: "Designated Managing Director", hint: "Person responsible for post-market safety management" },
        { id: "device_name_generic", label: "Device Name (Generic)", hint: "MHLW-recognized generic name from designated device list" },
        { id: "device_name_brand", label: "Device Name (Brand)", hint: "Commercial brand name and model" },
        { id: "classification", label: "Classification (Designated)", hint: "Class III designated (Ninsho) medical device per MHLW designated list" },
        { id: "rcb", label: "Registered Certification Body", hint: "MHLW-registered certification body performing the Ninsho review" },
      ]},
      { id: "sted", title: "STED (Summary Technical Documentation)", description: "Technical documentation for certification review", fields: [
        { id: "device_desc", label: "Device Description", hint: "Device description including principles of operation and structural composition", textarea: true },
        { id: "intended_use", label: "Intended Use / Indications", hint: "Intended purpose and specific clinical indications for Japan", textarea: true },
        { id: "principles", label: "Principles of Operation", hint: "Scientific and engineering principles underlying device function", textarea: true },
        { id: "design", label: "Design Characteristics", hint: "Design specifications, materials, and key dimensions", textarea: true },
        { id: "certification_std", label: "Certification Standards", hint: "MHLW certification standards (Ninsho Kijun) applicable to the device", textarea: true },
      ]},
      { id: "performance", title: "Performance & Safety Testing", description: "Testing against certification standards", fields: [
        { id: "jis_standards", label: "JIS Standards Testing", hint: "Test results per applicable JIS standards referenced in certification standards", textarea: true },
        { id: "performance_testing", label: "Performance Testing", hint: "Bench testing demonstrating compliance with MHLW certification standards", textarea: true },
        { id: "biocompat", label: "Biocompatibility", hint: "Biological evaluation per JIS T 0993 series", textarea: true },
        { id: "electrical_safety", label: "Electrical Safety (JIS T 0601)", hint: "Electrical safety per JIS T 0601-1 if applicable", textarea: true },
        { id: "emc", label: "EMC Testing", hint: "EMC testing per applicable JIS standards", textarea: true },
        { id: "sterilization", label: "Sterilization Validation", hint: "Sterilization validation per applicable standards if device is supplied sterile", textarea: true },
        { id: "stability", label: "Stability Studies", hint: "Shelf life and stability data supporting claimed product life", textarea: true },
        { id: "software", label: "Software Documentation", hint: "Software documentation per JIS T 2304 if device contains software", textarea: true },
      ]},
      { id: "clinical", title: "Clinical Data", description: "Clinical evidence for certification", fields: [
        { id: "clinical_eval", label: "Clinical Evaluation", hint: "Clinical evaluation demonstrating safety and efficacy for certification", textarea: true },
        { id: "literature", label: "Literature Review", hint: "Systematic review of published clinical literature for the device type", textarea: true },
        { id: "equivalence", label: "Equivalence to Certified Devices", hint: "Comparison with already-certified equivalent devices in Japan", textarea: true },
      ]},
      { id: "qms", title: "QMS Compliance", description: "Quality management system documentation", fields: [
        { id: "qms_169", label: "QMS Ordinance 169", hint: "QMS compliance documentation per MHLW Ordinance No.169", textarea: true },
        { id: "qms_audit", label: "QMS Audit by RCB", hint: "QMS audit performed by Registered Certification Body" },
        { id: "iso_13485", label: "ISO 13485 Certificate", hint: "Current ISO 13485 certificate covering the product manufacturing scope" },
      ]},
      { id: "risk", title: "Risk Management", description: "Risk management documentation", fields: [
        { id: "risk_mgmt", label: "Risk Management File", hint: "Complete risk management file per JIS T 14971 (ISO 14971)", textarea: true },
        { id: "fmea", label: "FMEA", hint: "Failure mode and effects analysis for device and process", textarea: true },
      ]},
      { id: "mfg", title: "Manufacturing Information", description: "Manufacturing sites and processes", fields: [
        { id: "mfg_sites", label: "Manufacturing Sites", hint: "All manufacturing and sterilization site information", textarea: true },
        { id: "process_overview", label: "Process Overview", hint: "Manufacturing process flow and critical control points", textarea: true },
        { id: "quality_control", label: "Quality Control", hint: "QC inspection methods and acceptance criteria", textarea: true },
      ]},
      { id: "labeling", title: "Labelling", description: "Japanese language labelling", fields: [
        { id: "labels_jp", label: "Japanese Labels", hint: "All labels in Japanese per PAL and MHLW labelling requirements", textarea: true },
        { id: "ifu_jp", label: "IFU in Japanese", hint: "Instructions for use in Japanese with all required warnings and precautions", textarea: true },
        { id: "packaging", label: "Packaging", hint: "Primary and secondary packaging with required Japanese labelling elements", textarea: true },
      ]},
      { id: "postmarket", title: "Post-Market Requirements", description: "Post-market surveillance and safety", fields: [
        { id: "safety_measures", label: "Post-Market Safety Measures", hint: "GVP-compliant safety management plan for certified device", textarea: true },
        { id: "adverse_reporting", label: "Adverse Event Reporting", hint: "Adverse event reporting to PMDA per PAL requirements", textarea: true },
        { id: "recall_plan", label: "Recall Procedures", hint: "Product recall procedures per MHLW recall notification", textarea: true },
      ]},
      { id: "jp_cert_specific", title: "Certification-Specific Requirements", description: "Additional requirements for Ninsho pathway", fields: [
        { id: "rcb_consultation", label: "RCB Pre-Submission Consultation", hint: "Pre-submission meeting records with the Registered Certification Body" },
        { id: "accredited_foreign_mfr", label: "Accredited Foreign Manufacturer", hint: "MHLW foreign manufacturer accreditation number and certificate" },
        { id: "cert_standards_ref", label: "Certification Standards Reference", hint: "Specific MHLW Ninsho Kijun standard number with applicable edition", textarea: true },
        { id: "equivalence_cert", label: "Equivalence to Certified Device", hint: "Comparison table with an already-certified device of the same category", textarea: true },
        { id: "jis_declaration", label: "JIS Conformity Declaration", hint: "Declaration of conformity to all applicable JIS standards listed in certification standards", textarea: true },
        { id: "mhlw_fee", label: "Application Fee", hint: "Certification application fee payment receipt" },
        { id: "free_sale_cert", label: "Free Sale Certificate", hint: "Free sale certificate from country of origin for certification review" },
        { id: "iso_13485_cert", label: "ISO 13485 Certificate", hint: "ISO 13485 certificate covering the product manufacturing scope" },
      ]},
    ],
  },
  {
    id: "JP_NOTIFICATION", countryCode: "JP", countryName: "Japan", flag: "🇯🇵", authority: "PMDA/MHLW", documentType: "Notification (Todokede)",
    sections: [
      { id: "admin", title: "Administrative Information", description: "MAH and device identification", fields: [
        { id: "mah", label: "Marketing Authorization Holder (MAH)", hint: "Japanese MAH name, address, and license number" },
        { id: "dmah", label: "DMAH (if foreign)", hint: "Designated Marketing Authorization Holder if foreign manufacturer" },
        { id: "device_name_generic", label: "Device Name (Generic)", hint: "MHLW-recognized generic device name" },
        { id: "device_name_brand", label: "Device Name (Brand)", hint: "Commercial brand name" },
        { id: "classification", label: "Classification (General/Controlled)", hint: "Class I (general) or Class II (controlled) medical device classification" },
      ]},
      { id: "device_info", title: "Device Information", description: "Device description and intended use", fields: [
        { id: "device_desc", label: "Device Description", hint: "Description of the device including composition, structure, and principle of operation", textarea: true },
        { id: "intended_use", label: "Intended Use", hint: "Intended purpose and conditions of use", textarea: true },
        { id: "specs", label: "Technical Specifications", hint: "Performance specifications, dimensions, materials used", textarea: true },
        { id: "accessories", label: "Accessories and Components", hint: "Accessories and components supplied with the device", textarea: true },
      ]},
      { id: "performance", title: "Performance & Safety", description: "Basic performance and safety documentation", fields: [
        { id: "performance_data", label: "Performance Data", hint: "Basic performance testing data demonstrating device function", textarea: true },
        { id: "safety_data", label: "Safety Data", hint: "Safety testing results relevant to device risk level", textarea: true },
        { id: "biocompat", label: "Biocompatibility (if applicable)", hint: "Biological evaluation per JIS T 0993 if device contacts patient", textarea: true },
        { id: "electrical_safety", label: "Electrical Safety (if applicable)", hint: "Electrical safety per JIS T 0601-1 if electrically powered device", textarea: true },
        { id: "sterilization", label: "Sterilization (if applicable)", hint: "Sterilization method and validation if supplied sterile", textarea: true },
        { id: "stability", label: "Stability Data", hint: "Shelf life data if applicable", textarea: true },
      ]},
      { id: "qms", title: "QMS Compliance", description: "Quality management system documentation", fields: [
        { id: "qms_169", label: "QMS Ordinance 169", hint: "QMS documentation per MHLW Ordinance (simplified requirements for Class I/II)", textarea: true },
        { id: "iso_13485", label: "ISO 13485 Certificate", hint: "ISO 13485 QMS certificate if available" },
      ]},
      { id: "risk", title: "Risk Management", description: "Basic risk management", fields: [
        { id: "risk_analysis", label: "Risk Analysis", hint: "Risk analysis appropriate to device classification level", textarea: true },
        { id: "risk_controls", label: "Risk Control Measures", hint: "Risk controls implemented and residual risk assessment", textarea: true },
      ]},
      { id: "labeling", title: "Labelling", description: "Japanese language labelling", fields: [
        { id: "labels_jp", label: "Japanese Labels", hint: "Labels in Japanese per PAL and MHLW notification-class labelling rules", textarea: true },
        { id: "ifu_jp", label: "IFU in Japanese", hint: "Instructions for use in Japanese appropriate for device class", textarea: true },
        { id: "packaging", label: "Packaging", hint: "Package labelling with required Japanese elements", textarea: true },
      ]},
      { id: "postmarket", title: "Post-Market", description: "Basic post-market requirements", fields: [
        { id: "safety_measures", label: "Safety Information Management", hint: "Basic safety information collection and management plan", textarea: true },
        { id: "adverse_reporting", label: "Adverse Event Reporting", hint: "Procedures for reporting adverse events to PMDA", textarea: true },
        { id: "recall_plan", label: "Recall Procedures", hint: "Product recall procedures if safety issue identified", textarea: true },
      ]},
      { id: "jp_notif_specific", title: "Notification-Specific Requirements", description: "Additional documentation for Todokede pathway", fields: [
        { id: "accredited_foreign_mfr", label: "Accredited Foreign Manufacturer", hint: "MHLW foreign manufacturer accreditation if applicable for Class II" },
        { id: "mah_license", label: "MAH Manufacturing/Marketing License", hint: "MAH license type (Type 1 for Class I, Type 2 for Class II) with license number" },
        { id: "notification_form", label: "Notification Form (Todokede)", hint: "MHLW-prescribed notification form with all required administrative fields", textarea: true },
        { id: "jis_declaration", label: "JIS Conformity Declaration", hint: "Declaration of conformity to applicable JIS standards if relevant", textarea: true },
        { id: "class_justification", label: "Classification Justification", hint: "Rationale for Class I or Class II classification per MHLW Ministerial Ordinance", textarea: true },
        { id: "foreign_approvals", label: "Foreign Regulatory Approvals", hint: "Approval status in US, EU, and other major markets if applicable", textarea: true },
        { id: "product_catalog", label: "Product Catalogue", hint: "Product catalogue with photographs, models, and basic specifications", textarea: true },
        { id: "mhlw_fee_notif", label: "Application Fee", hint: "Notification filing fee payment receipt" },
        { id: "import_notification", label: "Import Notification", hint: "Customs import notification documentation for foreign manufactured devices" },
        { id: "storage_conditions", label: "Storage and Transport Conditions", hint: "Required storage temperature, humidity, and transport conditions" },
      ]},
    ],
  },
];
