import type { RegulatoryFramework } from "../types";

export const KR_FRAMEWORKS: RegulatoryFramework[] = [
  {
    id: "KR_MFDS_TF", countryCode: "KR", countryName: "South Korea", flag: "🇰🇷", authority: "MFDS", documentType: "Technical File Review",
    sections: [
      { id: "admin", title: "Administrative Information", description: "Applicant, Korean agent, and device identification", fields: [
        { id: "applicant", label: "Applicant Information", hint: "Foreign manufacturer name, address, and business registration" },
        { id: "korean_agent", label: "Korean Agent", hint: "Licensed Korean importer or authorized representative with MFDS registration" },
        { id: "device_name_kr", label: "Device Name (Korean)", hint: "Device name in Korean per MFDS medical device naming conventions" },
        { id: "device_name_en", label: "Device Name (English)", hint: "Original device name in English" },
        { id: "mfds_class", label: "MFDS Classification (Class I-IV)", hint: "Risk classification per MFDS Medical Device Act (Class I, II, III, or IV)" },
        { id: "product_code", label: "Product Code", hint: "MFDS medical device item code and standard code" },
      ]},
      { id: "device_desc", title: "Device Description", description: "Technical description and intended use", fields: [
        { id: "description", label: "Device Description", hint: "Comprehensive description of the device including structure and composition", textarea: true },
        { id: "intended_use", label: "Intended Use", hint: "Specific medical intended use, clinical indication, and target population", textarea: true },
        { id: "specifications", label: "Technical Specifications", hint: "Performance specifications, dimensions, weight, power requirements", textarea: true },
        { id: "materials", label: "Materials", hint: "All materials used in the device including patient-contacting materials with grade", textarea: true },
        { id: "components", label: "Components", hint: "Component list with name, material, function, and supplier information", textarea: true },
        { id: "software", label: "Software", hint: "Software name, version, classification level, and intended function", textarea: true },
        { id: "accessories", label: "Accessories", hint: "All accessories, consumables, and companion devices", textarea: true },
        { id: "principle", label: "Principle of Operation", hint: "Scientific and engineering principles underlying device operation", textarea: true },
      ]},
      { id: "quality", title: "Quality System", description: "ISO 13485 and KGMP compliance", fields: [
        { id: "iso_13485", label: "ISO 13485 Certificate", hint: "Current ISO 13485 certificate from accredited certification body" },
        { id: "kgmp", label: "KGMP Certificate", hint: "Korea Good Manufacturing Practice certificate per MFDS requirements" },
        { id: "gmp_audit", label: "GMP Audit Report", hint: "MFDS GMP audit report or recognized third-party GMP audit results" },
        { id: "quality_manual", label: "Quality Manual Summary", hint: "Overview of QMS including quality policy, organizational structure, and key processes", textarea: true },
      ]},
      { id: "tech_specs", title: "Technical Specifications", description: "Product standards and engineering documentation", fields: [
        { id: "product_standards", label: "Product Standards", hint: "Applicable Korean and international product standards with conformity declaration", textarea: true },
        { id: "performance_specs", label: "Performance Specifications", hint: "Detailed performance specifications with acceptance criteria and test methods", textarea: true },
        { id: "drawings", label: "Dimensional Drawings", hint: "Engineering drawings with critical dimensions and tolerances", textarea: true },
        { id: "schematics", label: "Engineering Schematics", hint: "Circuit diagrams, block diagrams, and system architecture drawings", textarea: true },
      ]},
      { id: "testing", title: "Testing & Performance", description: "Safety and performance testing per Korean standards", fields: [
        { id: "ks_standards", label: "Korean Industrial Standards (KS)", hint: "Testing per applicable KS standards including KS C IEC series", textarea: true },
        { id: "biocompat", label: "Biocompatibility", hint: "Biological evaluation per KS P ISO 10993 series with test reports", textarea: true },
        { id: "electrical_safety", label: "Electrical Safety (KS C IEC 60601)", hint: "Electrical safety testing per KS C IEC 60601-1 and particular standards", textarea: true },
        { id: "emc", label: "EMC Testing", hint: "Electromagnetic compatibility per KS C IEC 60601-1-2", textarea: true },
        { id: "sterilization", label: "Sterilization Validation", hint: "Sterilization method validation per applicable KS/ISO standards", textarea: true },
        { id: "stability", label: "Stability / Shelf Life", hint: "Accelerated and real-time aging data supporting claimed shelf life", textarea: true },
        { id: "packaging", label: "Packaging Validation", hint: "Package integrity and transport simulation testing", textarea: true },
      ]},
      { id: "clinical", title: "Clinical Evaluation", description: "Clinical evidence assessment", fields: [
        { id: "clinical_data", label: "Clinical Data", hint: "Clinical evaluation or clinical investigation data per MFDS clinical requirements", textarea: true },
        { id: "literature", label: "Literature Review", hint: "Systematic review of published clinical literature for equivalent devices", textarea: true },
        { id: "equivalence", label: "Equivalence Analysis", hint: "Substantial equivalence comparison with legally marketed device in Korea", textarea: true },
      ]},
      { id: "risk", title: "Risk Management", description: "Risk management per ISO 14971", fields: [
        { id: "risk_mgmt", label: "Risk Management (ISO 14971)", hint: "Complete risk management file per KS P ISO 14971", textarea: true },
        { id: "hazard_analysis", label: "Hazard Analysis", hint: "Systematic hazard identification for all hazard categories", textarea: true },
        { id: "fmea", label: "FMEA", hint: "Failure mode and effects analysis for device and manufacturing processes", textarea: true },
      ]},
      { id: "labeling", title: "Labelling", description: "Korean language labelling requirements", fields: [
        { id: "labels_kr", label: "Korean Labels", hint: "All labels in Korean per MFDS Medical Device Act labelling requirements", textarea: true },
        { id: "ifu_kr", label: "IFU in Korean", hint: "Complete instructions for use in Korean with precautions and contraindications", textarea: true },
        { id: "packaging_labels", label: "Packaging Labels", hint: "Primary, secondary, and shipping package labelling in Korean", textarea: true },
        { id: "lot_serial", label: "Lot/Serial Marking", hint: "Lot number and serial number marking requirements per MFDS" },
      ]},
      { id: "mfg", title: "Manufacturing", description: "Manufacturing process and facilities", fields: [
        { id: "process_desc", label: "Process Description", hint: "Complete manufacturing process flow with critical process steps", textarea: true },
        { id: "facilities", label: "Manufacturing Facilities", hint: "Facility name, address, scope, and cleanroom classification if applicable", textarea: true },
        { id: "raw_materials", label: "Raw Material Specifications", hint: "Raw material specifications, suppliers, and incoming inspection criteria", textarea: true },
        { id: "storage_transport", label: "Storage and Transport", hint: "Storage conditions, transport requirements, and cold chain management if applicable", textarea: true },
      ]},
      { id: "postmarket", title: "Post-Market Surveillance", description: "Post-market monitoring and reporting", fields: [
        { id: "surveillance", label: "Post-Market Surveillance Plan", hint: "Systematic post-market surveillance plan per MFDS requirements", textarea: true },
        { id: "adverse_reporting", label: "Adverse Event Reporting", hint: "Adverse event reporting procedures and timelines per Medical Device Act", textarea: true },
        { id: "recall", label: "Recall Procedures", hint: "Device recall classification and procedures per MFDS recall regulations", textarea: true },
      ]},
      { id: "kr_specific", title: "Country-Specific Requirements", description: "MFDS-specific regulatory documentation", fields: [
        { id: "power_of_attorney", label: "Power of Attorney", hint: "Notarized power of attorney from manufacturer to Korean agent/importer" },
        { id: "free_sale_cert", label: "Free Sale Certificate", hint: "Certificate of free sale from country of origin apostilled or legalized" },
        { id: "iso_13485_cert", label: "ISO 13485 Certificate", hint: "ISO 13485 QMS certificate from KAS or IAF MLA-accredited body" },
        { id: "kgmp_application", label: "KGMP Audit Application", hint: "Application for MFDS GMP audit with manufacturing site documentation" },
        { id: "mfds_testing", label: "MFDS Testing Lab Report", hint: "Test report from MFDS-designated testing laboratory (KFDA-recognized lab)" },
        { id: "kr_insurance", label: "Product Liability Insurance", hint: "Product liability insurance certificate covering the Korean market" },
        { id: "import_license", label: "Import License", hint: "Korean medical device import business license from MFDS" },
        { id: "kr_declaration", label: "Conformity Declaration", hint: "Manufacturer's declaration of conformity to MFDS technical standards" },
        { id: "technical_doc_kr", label: "Korean Technical Document", hint: "Technical file summary translated into Korean per MFDS submission requirements", textarea: true },
      ]},
    ],
  },
  {
    id: "KR_MFDS_SER", countryCode: "KR", countryName: "South Korea", flag: "🇰🇷", authority: "MFDS", documentType: "Safety & Efficacy Review",
    sections: [
      { id: "admin", title: "Administrative Information", description: "Applicant, Korean agent, and device identification", fields: [
        { id: "applicant", label: "Applicant Information", hint: "Foreign manufacturer name, address, and business registration" },
        { id: "korean_agent", label: "Korean Agent", hint: "Licensed Korean importer or authorized representative with MFDS registration" },
        { id: "device_name_kr", label: "Device Name (Korean)", hint: "Device name in Korean per MFDS medical device naming rules" },
        { id: "device_name_en", label: "Device Name (English)", hint: "Original device name in English" },
        { id: "mfds_class", label: "MFDS Classification (Class III-IV)", hint: "High-risk classification per MFDS Medical Device Act (Class III or IV)" },
        { id: "product_code", label: "Product Code", hint: "MFDS medical device item code and standard code for high-risk devices" },
      ]},
      { id: "device_desc", title: "Device Description", description: "Technical description and intended use", fields: [
        { id: "description", label: "Device Description", hint: "Comprehensive device description including structure, composition, and operating principle", textarea: true },
        { id: "intended_use", label: "Intended Use", hint: "Specific medical intended use, target patient population, and clinical setting", textarea: true },
        { id: "specifications", label: "Technical Specifications", hint: "Detailed performance specifications, dimensions, operating parameters", textarea: true },
        { id: "materials", label: "Materials and Composition", hint: "All materials including biological origin, patient-contacting materials with biocompatibility data", textarea: true },
        { id: "components", label: "Components", hint: "Critical component list with material, function, supplier, and qualification", textarea: true },
        { id: "software", label: "Software", hint: "Software description, version, safety classification, and cybersecurity features", textarea: true },
        { id: "accessories", label: "Accessories", hint: "All accessories, consumables, and companion devices with descriptions", textarea: true },
        { id: "principle", label: "Principle of Operation", hint: "Detailed scientific and engineering principles with mode of action description", textarea: true },
      ]},
      { id: "quality", title: "Quality System", description: "ISO 13485 and KGMP compliance", fields: [
        { id: "iso_13485", label: "ISO 13485 Certificate", hint: "Current ISO 13485 QMS certificate from IAF MLA-accredited body" },
        { id: "kgmp", label: "KGMP Certificate", hint: "Korea Good Manufacturing Practice certificate per MFDS regulations" },
        { id: "gmp_audit", label: "GMP Audit Report", hint: "MFDS GMP on-site audit report for high-risk device manufacturing" },
        { id: "quality_manual", label: "Quality Manual Summary", hint: "QMS overview including quality policy, design controls, and CAPA process", textarea: true },
      ]},
      { id: "tech_specs", title: "Technical Specifications", description: "Product standards and engineering documentation", fields: [
        { id: "product_standards", label: "Product Standards", hint: "All applicable Korean (KS) and international standards with conformity evidence", textarea: true },
        { id: "performance_specs", label: "Performance Specifications", hint: "Critical performance specifications with detailed test methods and acceptance criteria", textarea: true },
        { id: "drawings", label: "Dimensional Drawings", hint: "Engineering drawings with critical dimensions, tolerances, and material callouts", textarea: true },
        { id: "schematics", label: "Engineering Schematics", hint: "Circuit diagrams, system architecture, pneumatic/hydraulic schematics", textarea: true },
      ]},
      { id: "testing", title: "Testing & Performance", description: "Comprehensive safety and performance testing", fields: [
        { id: "ks_standards", label: "Korean Industrial Standards (KS)", hint: "Complete testing per applicable KS standards series", textarea: true },
        { id: "biocompat", label: "Biocompatibility", hint: "Comprehensive biological evaluation per KS P ISO 10993 series with all required endpoints", textarea: true },
        { id: "electrical_safety", label: "Electrical Safety (KS C IEC 60601)", hint: "Complete electrical safety per KS C IEC 60601-1 and all applicable collateral/particular standards", textarea: true },
        { id: "emc", label: "EMC Testing", hint: "Full EMC testing per KS C IEC 60601-1-2 including emissions and immunity", textarea: true },
        { id: "sterilization", label: "Sterilization Validation", hint: "Complete sterilization process validation with bioburden and SAL verification", textarea: true },
        { id: "stability", label: "Stability / Shelf Life", hint: "Comprehensive accelerated and real-time aging studies with statistical analysis", textarea: true },
        { id: "packaging", label: "Packaging Validation", hint: "Sterile barrier validation per ISO 11607 and transport simulation testing", textarea: true },
        { id: "mechanical", label: "Mechanical Testing", hint: "Fatigue, wear, strength, and durability testing for implantable/load-bearing devices", textarea: true },
      ]},
      { id: "clinical_investigation", title: "Clinical Investigation", description: "Clinical trial data for high-risk devices", fields: [
        { id: "clinical_protocol", label: "Clinical Trial Protocol", hint: "MFDS-approved clinical trial protocol with study design and endpoints", textarea: true },
        { id: "clinical_data", label: "Clinical Trial Data", hint: "Complete clinical trial report with results per MFDS clinical trial regulations", textarea: true },
        { id: "statistical_analysis", label: "Statistical Analysis", hint: "Pre-specified statistical analysis plan and independent statistical report", textarea: true },
        { id: "safety_monitoring", label: "Safety Monitoring", hint: "Data safety monitoring board reports and serious adverse event summaries", textarea: true },
        { id: "irb_approval", label: "IRB Approval", hint: "Institutional Review Board approval documentation for each clinical site" },
      ]},
      { id: "clinical_eval", title: "Clinical Evaluation", description: "Clinical evidence assessment", fields: [
        { id: "clinical_eval_report", label: "Clinical Evaluation Report", hint: "Comprehensive clinical evaluation of all clinical evidence", textarea: true },
        { id: "literature", label: "Literature Review", hint: "Systematic review of published clinical literature per MFDS guidelines", textarea: true },
        { id: "equivalence", label: "Equivalence Analysis", hint: "Detailed equivalence analysis with legally marketed device in Korea", textarea: true },
      ]},
      { id: "risk", title: "Risk Management", description: "Comprehensive risk management", fields: [
        { id: "risk_mgmt", label: "Risk Management (ISO 14971)", hint: "Complete risk management file per KS P ISO 14971 for high-risk device", textarea: true },
        { id: "hazard_analysis", label: "Hazard Analysis", hint: "Comprehensive hazard identification covering all foreseeable hazard categories", textarea: true },
        { id: "fmea", label: "FMEA", hint: "Design and process FMEA with severity, occurrence, and detection ratings", textarea: true },
        { id: "residual_risk", label: "Residual Risk Evaluation", hint: "Overall residual risk acceptability and benefit-risk analysis", textarea: true },
      ]},
      { id: "labeling", title: "Labelling", description: "Korean language labelling requirements", fields: [
        { id: "labels_kr", label: "Korean Labels", hint: "All labels in Korean per MFDS Medical Device Act labelling requirements", textarea: true },
        { id: "ifu_kr", label: "IFU in Korean", hint: "Comprehensive IFU in Korean with warnings, precautions, and contraindications", textarea: true },
        { id: "packaging_labels", label: "Packaging Labels", hint: "Primary, secondary, and shipping package labelling in Korean", textarea: true },
        { id: "lot_serial", label: "Lot/Serial Marking", hint: "Lot number and serial number marking requirements" },
      ]},
      { id: "mfg", title: "Manufacturing", description: "Manufacturing process and facilities", fields: [
        { id: "process_desc", label: "Process Description", hint: "Complete manufacturing process flow with all critical control points", textarea: true },
        { id: "facilities", label: "Manufacturing Facilities", hint: "All facility information including cleanroom classifications and environmental controls", textarea: true },
        { id: "raw_materials", label: "Raw Material Specifications", hint: "Raw material specifications, supplier qualification, and traceability", textarea: true },
        { id: "storage_transport", label: "Storage and Transport", hint: "Storage conditions, transport requirements, and distribution chain controls", textarea: true },
      ]},
      { id: "postmarket", title: "Post-Market Surveillance", description: "Enhanced post-market monitoring for high-risk devices", fields: [
        { id: "surveillance", label: "Post-Market Surveillance Plan", hint: "Enhanced surveillance plan for high-risk devices per MFDS requirements", textarea: true },
        { id: "adverse_reporting", label: "Adverse Event Reporting", hint: "Adverse event reporting with expedited timelines for Class III/IV devices", textarea: true },
        { id: "recall", label: "Recall Procedures", hint: "Device recall classification and corrective action procedures", textarea: true },
        { id: "periodic_report", label: "Periodic Safety Report", hint: "Periodic safety update reporting requirements for high-risk devices", textarea: true },
      ]},
      { id: "kr_specific_ser", title: "Country-Specific Requirements", description: "MFDS-specific documentation for high-risk devices", fields: [
        { id: "power_of_attorney", label: "Power of Attorney", hint: "Notarized and apostilled power of attorney from manufacturer to Korean agent" },
        { id: "free_sale_cert", label: "Free Sale Certificate", hint: "Apostilled certificate of free sale from country of origin" },
        { id: "iso_13485_cert", label: "ISO 13485 Certificate", hint: "ISO 13485 QMS certificate from KAS or IAF MLA-accredited body" },
        { id: "kgmp_application", label: "KGMP On-Site Audit", hint: "MFDS on-site GMP audit application for high-risk device manufacturing facility" },
        { id: "mfds_testing", label: "MFDS Testing Lab Report", hint: "Complete test report from MFDS-designated testing laboratory" },
        { id: "kr_insurance", label: "Product Liability Insurance", hint: "Product liability insurance for high-risk device distribution in Korea" },
      ]},
    ],
  },
];
